engine/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@index');

    Route::group(['middleware' => ['admin']], function () {
        Route::get('/admin', function () {
            dd('aa');
        });
    });
    Route::get('get/{category_id}/spesification', 'Controller@getSpesification')->name('get.subcategory');
    Route::get('get/{category_id}/sub_category', 'Controller@getSubCategory')->name('get.subcategory');
    Route::get('get/{province_id}/cities', 'Controller@getCities')->name('get.city');
    Route::get('get/{city_id}/districts', 'Controller@getDistricts')->name('get.district');
    Route::get('get/{district_id}/areas', 'Controller@getAreas')->name('get.area');

    Route::resource('user', 'UserController');
    Route::post('user/{user_id}/updaterole', 'UserController@updateRole')->name('user.updaterole');
    Route::post('user/{user_id}/updatestatus', 'UserController@updateStatus')->name('user.updatestatus');
    Route::resource('member', 'MemberController');
    Route::get('member/unverified/get', 'MemberController@unverifiedAccount')->name('member.unverified');
    Route::post('member/unverified/{member_id}/verify', 'MemberController@verifyAccount')->name('member.verify');
    Route::get('member_address/', 'MemberAddressController@index')->name('member_address.index');
    Route::get('member_address/{member_id}/show', 'MemberAddressController@show')->name('member_address.show');
    Route::get('member_address/{member_id}/create', 'MemberAddressController@create')->name('member_address.create');
    Route::post('member_address/{member_id}/store', 'MemberAddressController@store')->name('member_address.store');
    Route::get('member_address/{member_id}/edit/{address_id}', 'MemberAddressController@edit')->name('member_address.edit');
    Route::put('member_address/{member_id}/update/{address_id}', 'MemberAddressController@update')->name('member_address.update');
    Route::delete('member_address/{member_id}/destroy/{address_id}', 'MemberAddressController@destroy')->name('member_address.destroy');
    Route::resource('member_request', 'MemberRequestController');

    Route::resource('homepage_banner', 'HomeBannerController');
    Route::resource('catalog_banner', 'CatalogBannerController');
    Route::resource('catalog_brand', 'CatalogBrandController');
    Route::resource('catalog_promo_banner', 'CatalogPromoBannerController');
    Route::resource('catalog_special_banner', 'CatalogSpecialDealBannerController');
    Route::resource('homepage_bottom_menu', 'HomeBottomMenuController');
    Route::resource('homepage_top_menu', 'HomeTopMenuController');
    Route::resource('homepage_promo_banner', 'HomePromoBannerController');
    Route::resource('popup_banner', 'PopupBannerController');
    Route::post('popup_banner/{banner_id}/updatestatus', 'PopupBannerController@updateStatus')->name('popup_banner.update_status');

    Route::resource('blast_email', 'BlastEmailController');

    Route::resource('category', 'CategoryController');
    Route::resource('sub_category', 'SubCategoryController');

    Route::resource('item', 'ItemController');
    Route::get('item/{item_id}/review', 'ItemController@review')->name('item.review');

    //ajax
    Route::get('get/{item_id}/item', 'ItemVarianController@getVariantByItem');
    Route::get('get/{variant_id}/detail', 'ItemVarianController@getVariantDetail');

    Route::get('varian/{item_id}/varian', 'ItemVarianController@index')->name('variant.index');
    Route::get('varian/{item_id}/create', 'ItemVarianController@create')->name('variant.create');
    Route::post('varian/{item_id}/store', 'ItemVarianController@store')->name('variant.store');
    // Route::post('varian/{varaint_id}/update_stock', 'ItemVarianController@updateStock')->name('item.update_stock');
    Route::get('varian/{item_id}/edit/{variant_id}', 'ItemVarianController@edit')->name('variant.edit');
    Route::put('varian/{item_id}/update/{variant_id}', 'ItemVarianController@update')->name('variant.update');
    Route::delete('varian/{item_id}/destroy/{variant_id}', 'ItemVarianController@destroy')->name('variant.destroy');

    Route::resource('item_hot', 'ItemHotController');
    Route::resource('item_select', 'ItemSelectController');
    Route::resource('item_best', 'ItemBestController');
    Route::resource('item_newest', 'ItemNewestController');
    Route::resource('item_image', 'itemImageController');

    Route::resource('voucher', 'VoucherController');

    // dropzone tidak berguna
    Route::post('item/get/{item_id}/image', 'ItemController@getImage')->name('item.upload_image');
    Route::get('item/get/{item_id}/image', 'ItemController@getImage')->name('item.get_upload_image');
});

engine/resources/views/homepage_banner/create.blade.php
@extends('layouts.master')
@section('main_content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Homepage Banner</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Cms</a></li>
                        <li class="breadcrumb-item active">add homepage banner</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{route('homepage_banner.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="image_desktop">Banner Desktop</label>
                                    <div>
                                        <img src="" alt="" id="imgreview" style="max-width: 200px">
                                    </div>
                                    <input type="file" name="image_desktop" class="form-control" id="image_desktop"
                                        value="{{old('name')}}">
                                    @error('image_desktop')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="image_responsive">Banner Responsive</label>
                                    <div>
                                        <img src="" alt="" id="imgreview1" style="max-width: 200px">
                                    </div>
                                    <input type="file" name="image_responsive" class="form-control"
                                        id="image_responsive" value="{{old('image_responsive')}}">
                                    @error('image_responsive')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="url">Url</label>
                                    <input type="text" name="url" class="form-control" id="url" placeholder="url"
                                        value="{{old('url')}}">
                                    @error('url')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary float-right">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@push('js')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#imgreview').attr('src', e.target.result);
                $('#imgreview').css('padding', '15px');
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }

    $("#image_desktop").change(function() {
        readURL(this);
    });

    function readURL1(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#imgreview1').attr('src', e.target.result);
                $('#imgreview1').css('padding', '15px');
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }

    $("#image_responsive").change(function() {
        readURL1(this);
    });
</script>
@endpush

engine/resources/views/homepage_banner/edit.blade.php
@extends('layouts.master')
@section('main_content')
@push('css')

@endpush
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Banner</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Cms</a></li>
                        <li class="breadcrumb-item active">edit homepage banner</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title"></h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{route('homepage_banner.update', $banner->id)}}"
                            enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="image_desktop">Image Desktop</label>
                                    <div>
                                        <img src="{{asset($banner->image_desktop)}}" alt="" id="imgreview">
                                    </div>
                                    <input type="file" name="image_desktop" class="form-control" id="image_desktop">
                                    @error('image_desktop')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="image_responsive">Image Responsive</label>
                                    <div>
                                        <img src="{{asset($banner->image_responsive)}}" alt="" id="imgreview1">
                                    </div>
                                    <input type="file" name="image_responsive" class="form-control"
                                        id="image_responsive">
                                    @error('image_responsive')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="url">Url</label>
                                    <input type="text" name="url" class="form-control" id="url" placeholder="url"
                                        value="{{$banner->url}}">
                                    @error('url')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary float-right">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@push('js')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#imgreview').attr('src', e.target.result);
                $('#imgreview').css('padding', '15px');
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }

    $("#image_desktop").change(function() {
        readURL(this);
    });

    function readURL1(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#imgreview1').attr('src', e.target.result);
                $('#imgreview1').css('padding', '15px');
            }

            reader.readAsDataURL(input.files[0]); // convert to base64 string
        }
    }

    $("#image_responsive").change(function() {
        readURL1(this);
    });
</script>
@endpush

engine/resources/views/homepage_banner/index.blade.php
@extends('layouts.master')
@section('main_content')
@push('css')
<style>
    td {
        max-width: 200px;
    }

    td img {
        max-width: inherit;
    }
</style>
@endpush
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Homepage Banner</h1>
                    <a class="btn btn-primary mt-3" href="{{route('homepage_banner.create')}}">Add New Banner</a>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Cms</a></li>
                        <li class="breadcrumb-item active">homepage banner</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">

                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Banner Desktop</th>
                                        <th>Banner Responsive</th>
                                        <th>Url</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($banners as $banner)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td><img src="{{asset($banner->image_desktop)}}" alt=""></td>
                                        <td><img src="{{asset($banner->image_responsive)}}" alt=""></td>
                                        <td>{{$banner->url}}</td>
                                        <td class="text-center">
                                            <a class="nav-link dropdown-toggle btn btn-primary" style="display: unset" data-toggle="dropdown" href="#">
                                                Menu <span class="caret"></span>
                                            </a>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" tabindex="-1"
                                                    href="{{route('homepage_banner.edit', $banner->id)}}">Edit</a>
                                                <a class="dropdown-item" tabindex="-1" href="#"
                                                    onclick="destroy({{$banner->id}})">Delete</a>
                                            </div>
                                            <form method="POST" id="formdelete-{{$banner->id}}"
                                                action="{{route("homepage_banner.destroy",$banner->id)}}">
                                                @csrf
                                                @method("delete")
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@push('js')
<script>
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
    });
    $( document ).ready(function() {
        $('.table').DataTable({
            "responsive": true,
            "autoWidth": false,
        });
    });
    function destroy(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value == true) {
                $("#formdelete-" + id).submit();
            }
        })
    }
</script>

@if ($message = Session::get('success'))
<script>
    Toast.fire({
        icon: 'success',
        title: '  {{ $message }}'
    })
</script>
@endif
@endpush