engine/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@index');

    Route::group(['middleware' => ['admin']], function () {
        Route::get('/admin', function () {
            dd('aa');
        });
    });
    Route::get('get/{category_id}/spesification', 'Controller@getSpesification')->name('get.subcategory');
    Route::get('get/{category_id}/sub_category', 'Controller@getSubCategory')->name('get.subcategory');
    Route::get('get/{province_id}/cities', 'Controller@getCities')->name('get.city');
    Route::get('get/{city_id}/districts', 'Controller@getDistricts')->name('get.district');
    Route::get('get/{district_id}/areas', 'Controller@getAreas')->name('get.area');

    Route::resource('user', 'UserController');
    Route::post('user/{user_id}/updaterole', 'UserController@updateRole')->name('user.updaterole');
    Route::post('user/{user_id}/updatestatus', 'UserController@updateStatus')->name('user.updatestatus');
    Route::resource('member', 'MemberController');
    Route::get('member/unverified/get', 'MemberController@unverifiedAccount')->name('member.unverified');
    Route::post('member/unverified/{member_id}/verify', 'MemberController@verifyAccount')->name('member.verify');
    Route::get('member_address/', 'MemberAddressController@index')->name('member_address.index');
    Route::get('member_address/{member_id}/show', 'MemberAddressController@show')->name('member_address.show');
    Route::get('member_address/{member_id}/create', 'MemberAddressController@create')->name('member_address.create');
    Route::post('member_address/{member_id}/store', 'MemberAddressController@store')->name('member_address.store');
    Route::get('member_address/{member_id}/edit/{address_id}', 'MemberAddressController@edit')->name('member_address.edit');
    Route::put('member_address/{member_id}/update/{address_id}', 'MemberAddressController@update')->name('member_address.update');
    Route::delete('member_address/{member_id}/destroy/{address_id}', 'MemberAddressController@destroy')->name('member_address.destroy');
    Route::resource('member_request', 'MemberRequestController');

    Route::resource('homepage_banner', 'HomeBannerController');
    Route::resource('catalog_banner', 'CatalogBannerController');
    Route::resource('catalog_brand', 'CatalogBrandController');
    Route::resource('catalog_promo_banner', 'CatalogPromoBannerController');
    Route::resource('catalog_special_banner', 'CatalogSpecialDealBannerController');
    Route::resource('homepage_bottom_menu', 'HomeBottomMenuController');
    Route::resource('homepage_top_menu', 'HomeTopMenuController');
    Route::resource('homepage_promo_banner', 'HomePromoBannerController');
    Route::resource('popup_banner', 'PopupBannerController');
    Route::post('popup_banner/{banner_id}/updatestatus', 'PopupBannerController@updateStatus')->name('popup_banner.update_status');

    Route::resource('blast_email', 'BlastEmailController');

    Route::resource('category', 'CategoryController');
    Route::resource('sub_category', 'SubCategoryController');

    Route::resource('item', 'ItemController');
    Route::get('item/{item_id}/review', 'ItemController@review')->name('item.review');

    //ajax
    Route::get('get/{item_id}/item', 'ItemVarianController@getVariantByItem');
    Route::get('get/{variant_id}/detail', 'ItemVarianController@getVariantDetail');

    Route::get('varian/{item_id}/varian', 'ItemVarianController@index')->name('variant.index');
    Route::get('varian/{item_id}/create', 'ItemVarianController@create')->name('variant.create');
    Route::post('varian/{item_id}/store', 'ItemVarianController@store')->name('variant.store');
    // Route::post('varian/{varaint_id}/update_stock', 'ItemVarianController@updateStock')->name('item.update_stock');
    Route::get('varian/{item_id}/edit/{variant_id}', 'ItemVarianController@edit')->name('variant.edit');
    Route::put('varian/{item_id}/update/{variant_id}', 'ItemVarianController@update')->name('variant.update');
    Route::delete('varian/{item_id}/destroy/{variant_id}', 'ItemVarianController@destroy')->name('variant.destroy');

    Route::resource('item_hot', 'ItemHotController');
    Route::resource('item_select', 'ItemSelectController');
    Route::resource('item_best', 'ItemBestController');
    Route::resource('item_newest', 'ItemNewestController');
    Route::resource('item_image', 'itemImageController');

    Route::resource('voucher', 'VoucherController');

    // dropzone tidak berguna
    Route::post('item/get/{item_id}/image', 'ItemController@getImage')->name('item.upload_image');
    Route::get('item/get/{item_id}/image', 'ItemController@getImage')->name('item.get_upload_image');
});

engine/app/Models/ItemHot.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ItemHot extends Model
{
    use HasFactory;
    protected $guarded = [];

    // function product(){
    //     return $this->belongsTo('App\Models\Item', 'item_id');
    // }
    function variants(){
        return $this->belongsTo('App\Models\ItemStockVariant', 'variant_id');
    }
}

engine/app/Http/Controllers/ItemHotController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\ItemHot;
use App\Models\ItemStockVariant;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ItemHotController extends Controller
{
    public function index()
    {
        $d['items'] = ItemHot::with('variants')->get();
        return view('item_hot.index', $d);
    }

    public function create()
    {
        $d['items'] = Item::all();
        $d['variants'] = ItemStockVariant::all();
        return view('item_hot.create', $d);
    }

    public function store(Request $request)
    {
        ItemHot::create([
            'variant_id' => $request->variant_id,
        ]);

        $variant = ItemStockVariant::find($request->variant_id);
        $variant->discount_price = $request->variant_discount_price;
        $variant->start_deal = Carbon::parse($request->variant_start_deal);
        $variant->end_deal = Carbon::parse($request->variant_end_deal);
        $variant->save();
        return redirect(route('item_hot.index'))->with(['success' => " add new product success"]);
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $d['itemhot'] = ItemHot::with('variants.product')->find($id);
        $d['items'] = Item::all();
        return view('item_hot.edit', $d);
    }

    public function update(Request $request, $id)
    {

        $update = ItemHot::find($id);
        $update->variant_id = $request->variant_id;
        $update->save();

        $variant = ItemStockVariant::find($request->variant_id);
        $variant->discount_price = $request->variant_discount_price;
        $variant->start_deal = Carbon::parse($request->variant_start_deal);
        $variant->end_deal = Carbon::parse($request->variant_end_deal);
        $variant->save();

        return redirect(route('item_hot.index'))->with(['success' => " update product success"]);
    }

    public function destroy($id)
    {
        $category = ItemHot::find($id);
        $category->delete();
        return redirect()->back()->with(['success' => " delete category success"]);
    }
}

engine/resources/views/item_hot/create.blade.php
@extends('layouts.master')
@section('main_content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Product Hots</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Item</a></li>
                        <li class="breadcrumb-item active">add Product Hots</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{route('item_hot.store')}}"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="item_id">Product</label>
                                    <select class="form-control select2" name="item_id" id="item_id">
                                        @foreach ($items as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                    @error('item_id')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="variant_id">Variant</label>
                                    <select class="form-control select2" name="variant_id" id="variant_id">
                                    </select>
                                    @error('variant_id')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="variant-box col-12 row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="variant_discount_price">Discount Price</label>
                                            <input type="text" name="variant_discount_price" class="form-control"
                                                id="variant_discount_price" placeholder="Product discount_price"
                                                value="">
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="bootstrap-timepicker">
                                            <div class="form-group">
                                                <label for="end_deal">Discount Start Date</label>
                                                <div class="input-group date timepicker" id="timepicker_start"
                                                    data-target-input="nearest">
                                                    <input type="text" name="variant_start_deal"
                                                        class="form-control datetimepicker-input"
                                                        id="variant_start_deal" data-target="#timepicker_start"
                                                        value="" />
                                                    <div class="input-group-append" data-target="#timepicker_start"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-clock"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                @error('end_deal')
                                                <p class="text-danger">{{ $message }}</p>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="bootstrap-timepicker">
                                            <div class="form-group">
                                                <label for="end_deal">Discount End Date</label>
                                                <div class="input-group date timepicker" id="timepicker_end"
                                                    data-target-input="nearest">
                                                    <input type="text" name="variant_end_deal" id="variant_end_deal"
                                                        class="form-control datetimepicker-input"
                                                        data-target="#timepicker_end" value="" />
                                                    <div class="input-group-append" data-target="#timepicker_end"
                                                        data-toggle="datetimepicker">
                                                        <div class="input-group-text"><i class="fa fa-clock"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                @error('end_deal')
                                                <p class="text-danger">{{ $message }}</p>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary float-right">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@push('js')
<script>
    $( document ).ready(function() {
        $.fn.datetimepicker.Constructor.Default = $.extend({},
        $.fn.datetimepicker.Constructor.Default,
        { icons:{
            time: 'fas fa-clock',
            date: 'fas fa-calendar',
            up: 'fas fa-arrow-up',
            down: 'fas fa-arrow-down',
            previous: 'fas fa-arrow-circle-left'
            ,next: 'fas fa-arrow-circle-right',
            today: 'far fa-calendar-check-o',
            clear: 'fas fa-trash',
            close: 'far fa-times' } });
        $('.select2').select2({
            theme: 'bootstrap4',
        })
        $('.timepicker').datetimepicker({
            format: 'DD-MM-YYYY HH:mm'
        })
        $("#item_id").change();
    });

    $('#item_id').change(function(){
        var item_id = $('#item_id').find(":selected").val();
        $.ajax({
            url: `{{url('/')}}/get/`+item_id+`/item`,
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method: 'get',
            success: function (data){
                $('#variant_id').empty()
                $.each(data, function(index, val){
                    $('#variant_id').append(`<option value="`+val.id+`" >`+val.variant+`</option>`)
                })
                $("#variant_id").change();
            }
        })
    })

    $('#variant_id').change(function(){
        var variant_id = $('#variant_id').find(":selected").val();
        $("#variant_discount_price").val('')
        $("#variant_start_deal").val('')
        $("#variant_end_deal").val('')
        $.ajax({
            url: `{{url('/')}}/get/`+variant_id+`/detail`,
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method: 'get',
            success: function (data){
                $("#variant_discount_price").val(data.discount_price)
                $("#variant_start_deal").val(data.start_deal)
                $("#variant_end_deal").val(data.end_deal)
            }
        })
    })
</script>
@endpush

engine/resources/views/item_hot/index.blade.php
@extends('layouts.master')
@section('main_content')
@push('css')
<style>
    .width-200 {
        min-width: 200px;
    }

    .width-100 {
        min-width: 100px;
    }
</style>
@endpush
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Product Hot</h1>
                    <a class="btn btn-primary mt-3" href="{{route('item_hot.create')}}">Add New Product Hot</a>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item active">Product Hot</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">

                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table class="table table-bordered table-striped ">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Product</th>
                                        <th>Variant</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($items as $item)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td><a
                                                href="{{route('item.show',$item->variants->product->id)}}">{{$item->variants->product->name ?? ''}}</a>
                                        </td>
                                        <td><a
                                                href="{{route('variant.index',$item->variants->product->id)}}">{{$item->variants->variant ?? ''}}</a>
                                        </td>
                                        <td class="text-center width-200">
                                            <a class="nav-link dropdown-toggle btn btn-primary" style="display: unset"
                                                data-toggle="dropdown" href="#">
                                                Menu <span class="caret"></span>
                                            </a>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" tabindex="-1"
                                                    href="{{route('item_hot.edit', $item->id)}}">Edit</a>
                                                <a class="dropdown-item" tabindex="-1" href="#"
                                                    onclick="destroy({{$item->id}})">Delete</a>
                                            </div>
                                            <form method="POST" id="formdelete-{{$item->id}}"
                                                action="{{route("item_hot.destroy",$item->id)}}">
                                                @csrf
                                                @method("delete")
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection
@push('js')
<script>
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
    });
    $( document ).ready(function() {
        $('.table').DataTable({
            "autoWidth": false,
            "scrollX": true
        });
    });
    function destroy(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value == true) {
                $("#formdelete-" + id).submit();
            }
        })
    }
</script>

@if ($message = Session::get('success'))
<script>
    Toast.fire({
        icon: 'success',
        title: '  {{ $message }}'
    })
</script>
@endif
@endpush